.. _main:

==========
StarCogs
==========

This documentation is here for the support of my redbot cogs. Everything should be here that you need.

============
Useful Links
============

* `Github Repository <https://github.com/LeDeathAmongst/StarCogs>`_

.. toctree::
    :caption: Repository
    :maxdepth: 2

    repo_installation
    repo_license
    repo_support
    repo_telemetry

.. toctree::
    :caption: Cogs documentations
    :maxdepth: 1

    AAA3A_utils
    AFK
    AIEmote
    AIUser
    Activities
    AdWarn
    AddImage
    AdminToggle
    AdvancedBlacklist
    Adventure
    AdventureAlert
    Aki
    Aliases
    AltDentifier
    AltMarker
    AnonReporter
    AntiLinks
    AntiPhishing
    AsSky
    Assistant
    AssistantUtils
    AutoBan
    AutoConfigCleaner
    AutoDelete
    AutoDocs
    AutoGist
    AutoMod
    AutoPublisher
    AutoTraceback
    Automuter
    Autoreact
    Avatar
    Away
    Backup
    Badges
    BanAppeal
    BanChart
    Banana
    BankBackup
    BankEvents
    BannedCount
    Banner
    Bingo
    Bl
    BoostUtils
    BotLogger
    BrainfuckCog
    Bumper
    ButtonPoll
    COC
    Calculator
    CardsAgainstHumanity
    CaseInsensitive
    Casino
    Chatchart
    ChessGame
    Choose
    ClearChannel
    CodeSnippets
    CogManagerUI
    Color
    CommandsButtons
    ConsoleClearer
    Cooldown
    Core
    Counter
    Counting
    Coupon
    Crafter
    CtrlZ
    CustomHelp
    CustomPing
    CycleStatus
    DMAffiliates
    DallE
    DashIntGen
    Dashboard
    Dev
    DevUtils
    DiscordEdit
    DiscordModals
    DiscordSearch
    DisurlVotesTracker
    DontPingStaff
    Downloader
    DynamicPrefix
    EconomyTrickle
    EmbedCreator
    EmbedUtils
    EmojiInfo
    EmojiTools
    Encoding
    ErrorLogs
    EventLogger
    Events
    ExclusiveRoles
    ExtendedModLog
    FIFO
    FakeMod
    FastClickGame
    FeatureRequest
    Fluent
    FluxImgGen
    Forward
    Freshmeat
    GistsHandler
    GitHub
    Giveaways
    GlobalBan
    GuildID
    GuildManager
    Gulag
    Hellohook
    Hider
    HitOrMiss
    HostInfo
    HowGay
    Hue
    Hunting
    IdeaBoard
    ImageScanner
    Index
    InfiniCount
    InlineCommands
    InstaDelete
    Insult
    IntroCog
    InviteBlocklist
    InviteSettings
    Invites
    IsItDown
    Jail
    JoinPing
    Jokes
    KoFiTracker
    LastPing
    Leaver
    Lenny
    LevelUp
    LinkQuoter
    LinkStorage
    LinkWarner
    Lock
    Lockdown
    LuigiPoker
    MadTranslate
    Maintenance
    MemberCount
    MemberHistory
    MemberPrefix
    MemoryGame
    MessageCounter
    Minecraft
    ModLog
    ModManager
    Move
    MultiCommands
    NameChanger
    NetSpeed
    NickNamer
    NoBot
    NoDMs
    NoNuke
    NoSpoiler
    OnConnect
    OnEdit
    OnlyAllow
    Otherbot
    OwnerProtection
    Paginator
    PartyCrash
    PassGen
    PayDay
    Perform
    PersonalReact
    PhenUtils
    Pinboard
    Pingtime
    Pokemon
    PokemonDuel
    Praise
    Prefix
    PrivateWormHole
    ProjectPost
    Pupper
    Purge
    PyLavConfigurator
    PyLavController
    PyLavEffects
    PyLavLocalFiles
    PyLavLyrics
    PyLavManagedNode
    PyLavMigrator
    PyLavNodes
    PyLavNotifier
    PyLavPlayer
    PyLavPlaylists
    PyLavRadio
    PyLavUtils
    PyPi
    QR
    QRInvite
    Quarantine
    Quiz
    Race
    Raffle
    RandomEmoji
    RandomTopic
    Ratings
    ReTrigger
    RedUpdate
    Reminders
    RepoList
    RequestGB
    RestartMsg
    ReviewsCog
    RoleBoards
    RoleLocker
    RolePlay
    RoleRequests
    RoleTools
    RoleUtils
    RolesButtons
    RolloutGame
    Roomer
    RunCode
    Say
    Search
    SecureInv
    Seen
    SeinaTools
    SelfAssign
    SentryIO
    ServerAssistant
    ServerBlocker
    ServerInfo
    Shell
    Shop
    SimpleSanction
    Simulator
    Skyrim
    SlashRequest
    SlashTags
    SlowMode
    SmartReact
    Snipe
    SplitOrStealGame
    Spoop
    Star_Utils
    StickBugged
    Sticky
    StickyMember
    Strikes
    Sudo
    System
    TTT
    Tags
    Talk
    TeachMe
    TellMe
    TempRoles
    ThreadOpener
    TicketTool
    Ticks
    TimeChannel
    TimeStamps
    TimeoutSelf
    TongueTwisters
    TransferChannel
    TrickOrTreat
    Trigger
    Triggered
    UnbanAll
    Unbelievaboat
    UptimeResponder
    UrlButtons
    UselessFacts
    VerifyAll
    VirusTotal
    VoiceTools
    VrtUtils
    Webhook
    WelcomeCount
    Werewolf
    WordScramble
    Wormhole
    YTDownloader
    Zalgo
